name: autobuild

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      id: checkout
      uses: actions/checkout@main
      with:
        submodules: true
        fetch-depth: 0
    - name: Build
      id: build
      run: |
        make -j 3 || make -j1
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload Artifacts
      uses: actions/upload-artifact@main
      if: steps.build.outputs.status == 'success'
      with:
        name: main
        path: main
